### ISSUE TITLE
voice recorder issue

### ISSUE THREAD

**Issue by AAryanHitman** [Palakgupta26/Devops_VoiceRecorder#3]
<img width="487" alt="Screenshot 2023-09-24 at 10 03 57 PM" src="https://github.com/Palakgupta26/Devops_VoiceRecorder/assets/113382989/2edb4cae-7784-4c1d-9912-ce08a789e019">

There is an error as the voice is only recording for 5 seconds and its stopping automatically.

**Comment by Palakgupta26** [comment]
Output
![image](https://github.com/Palakgupta26/Devops_VoiceRecorder/assets/142999560/fd326ae6-d219-4e57-9cb2-006c014aea9c)
